USE [master]
GO
/****** Object:  Database [ObligatorioP3]    Script Date: 18/04/2022 20:12:29 ******/
CREATE DATABASE [ObligatorioP3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ObligatorioP^3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ObligatorioP^3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ObligatorioP^3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ObligatorioP^3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ObligatorioP3] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ObligatorioP3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ObligatorioP3] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ObligatorioP3] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ObligatorioP3] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ObligatorioP3] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ObligatorioP3] SET ARITHABORT OFF 
GO
ALTER DATABASE [ObligatorioP3] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ObligatorioP3] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ObligatorioP3] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ObligatorioP3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ObligatorioP3] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ObligatorioP3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ObligatorioP3] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ObligatorioP3] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ObligatorioP3] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ObligatorioP3] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ObligatorioP3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ObligatorioP3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ObligatorioP3] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ObligatorioP3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ObligatorioP3] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ObligatorioP3] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ObligatorioP3] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ObligatorioP3] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ObligatorioP3] SET  MULTI_USER 
GO
ALTER DATABASE [ObligatorioP3] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ObligatorioP3] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ObligatorioP3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ObligatorioP3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ObligatorioP3] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ObligatorioP3] SET QUERY_STORE = OFF
GO
USE [ObligatorioP3]
GO
/****** Object:  Table [dbo].[Ambientes]    Script Date: 18/04/2022 20:12:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ambientes](
	[idAmbiente] [int] IDENTITY(1,1) NOT NULL,
	[TipoAmbiente] [varchar](20) NOT NULL,
 CONSTRAINT [PK_Ambientes] PRIMARY KEY CLUSTERED 
(
	[idAmbiente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NombresVulgares]    Script Date: 18/04/2022 20:12:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NombresVulgares](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreVulgar] [nvarchar](20) NOT NULL,
	[idPlanta] [int] NOT NULL,
 CONSTRAINT [PK_NombresVulgares] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Plantas]    Script Date: 18/04/2022 20:12:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Plantas](
	[idPlanta] [int] IDENTITY(1,1) NOT NULL,
	[TipoPlanta] [int] NOT NULL,
	[NombreCientifico] [varchar](40) NOT NULL,
	[Descripcion] [varchar](100) NOT NULL,
	[Ambiente] [int] NOT NULL,
	[Altura] [decimal](5, 2) NOT NULL,
	[Foto] [varchar](50) NOT NULL,
	[FrecuenciaDeRiego] [varchar](20) NOT NULL,
	[Iluminacion] [int] NOT NULL,
	[TempMantenimiento] [int] NOT NULL,
 CONSTRAINT [PK_Plantas] PRIMARY KEY CLUSTERED 
(
	[idPlanta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [CK_NombreCientifico_Unique] UNIQUE NONCLUSTERED 
(
	[NombreCientifico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TiposDeIluminacion]    Script Date: 18/04/2022 20:12:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TiposDeIluminacion](
	[idIluminacion] [int] IDENTITY(1,1) NOT NULL,
	[TipoIluminacion] [varchar](20) NOT NULL,
 CONSTRAINT [PK_TiposDeIluminacion] PRIMARY KEY CLUSTERED 
(
	[idIluminacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TiposDePlanta]    Script Date: 18/04/2022 20:12:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TiposDePlanta](
	[idTipo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](30) NOT NULL,
	[Descripcion] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Tipo] PRIMARY KEY CLUSTERED 
(
	[idTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 18/04/2022 20:12:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[idUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Mail] [varchar](40) NOT NULL,
	[Pass] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[idUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NombresVulgares]  WITH CHECK ADD  CONSTRAINT [FK_NombresVulgares_Plantas] FOREIGN KEY([idPlanta])
REFERENCES [dbo].[Plantas] ([idPlanta])
GO
ALTER TABLE [dbo].[NombresVulgares] CHECK CONSTRAINT [FK_NombresVulgares_Plantas]
GO
ALTER TABLE [dbo].[Plantas]  WITH CHECK ADD  CONSTRAINT [FK_Plantas_Ambientes] FOREIGN KEY([Ambiente])
REFERENCES [dbo].[Ambientes] ([idAmbiente])
GO
ALTER TABLE [dbo].[Plantas] CHECK CONSTRAINT [FK_Plantas_Ambientes]
GO
ALTER TABLE [dbo].[Plantas]  WITH CHECK ADD  CONSTRAINT [FK_Plantas_TiposDeIluminacion] FOREIGN KEY([Iluminacion])
REFERENCES [dbo].[TiposDeIluminacion] ([idIluminacion])
GO
ALTER TABLE [dbo].[Plantas] CHECK CONSTRAINT [FK_Plantas_TiposDeIluminacion]
GO
ALTER TABLE [dbo].[Plantas]  WITH CHECK ADD  CONSTRAINT [FK_Plantas_TiposDePlanta] FOREIGN KEY([TipoPlanta])
REFERENCES [dbo].[TiposDePlanta] ([idTipo])
GO
ALTER TABLE [dbo].[Plantas] CHECK CONSTRAINT [FK_Plantas_TiposDePlanta]
GO
ALTER TABLE [dbo].[Plantas]  WITH CHECK ADD  CONSTRAINT [CK_Descripcion_length] CHECK  ((len([Descripcion])>=(10) AND len([Descripcion])<=(200)))
GO
ALTER TABLE [dbo].[Plantas] CHECK CONSTRAINT [CK_Descripcion_length]
GO
USE [master]
GO
ALTER DATABASE [ObligatorioP3] SET  READ_WRITE 
GO
